export const Locator = {
  EpisodeRepository: Symbol.for('EpisodeRepository'),
  EpisodeUseCase: Symbol.for('EpisodeUseCase'),
  CreateEpisodeController: Symbol.for('CreateEpisodeController'),
  CreateEpisodeControllerTrigger: Symbol.for('CreateEpisodeControllerTrigger'),
  EpisodeStoreUsecase: Symbol.for('EpisodeStoreUsecase'),
  EpisodeStoreController: Symbol.for('EpisodeStoreController'),
  ContractRepository: Symbol.for('ContractRepository'),
  MenuRepository: Symbol.for('MenuRepository'),
  EpisodePWAUseCase: Symbol.for('EpisodePWAUseCase'),
  EpisodePWAController: Symbol.for('EpisodePWAController'),
  UploadEpisodeLogo: Symbol.for('UploadEpisodeLogo'),
  UpdateEpisodeLogoHttp: Symbol.for('UpdateEpisodeLogoHttp'),
  GetEpisodeByCollabHttp: Symbol.for('GetEpisodeByCollabHttp'),
  UpdateEpisodeHttp: Symbol.for('UpdateEpisodeHttp'),
  PublishEpisodeUpdate: Symbol.for('PublishEpisodeUpdate'),
  IsShortLinkAvailable: Symbol.for('IsShortLinkAvailable'),
  GetEpisodeIdByShortLinkHttp: Symbol.for('GetEpisodeIdByShortLinkHttp'),
  OrderRepository: Symbol.for('OrderRepository'),
  GetEpisodeRevenuesHttp: Symbol.for('GetEpisodeRevenuesHttp'),
  GetEpisodeDeliveryTypesHttp: Symbol.for('GetEpisodeDeliveryTypesHttp'),
  GetEpisodePaymentTypesHttp: Symbol.for('GetEpisodePaymentTypesHttp'),
  GetEpisodeTaxAndDiscountsHttp: Symbol.for('GetEpisodeTaxAndDiscountsHttp'),
  GetEpisodePodiumHttp: Symbol.for('GetEpisodePodiumHttp'),
  GetEpisodeStockViewHttp: Symbol.for('GetEpisodeStockViewHttp'),
  GetEpisodeMenusHttp: Symbol.for('GetEpisodeMenusHttp'),
  GetEpisodeForPrepHttp: Symbol.for('GetEpisodeForPrepHttp'),
}
